apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: asdf
  description: Real description
  tags:
    - go
    - website
spec:
  type: service
  lifecycle: production
  owner: eng-team-1
